-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 15:36:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` BLOB NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `edad` INT NULL,
  `ciudad` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `contraseña` BLOB NOT NULL,
  `id_admin` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuario_admin1_idx` (`id_admin` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_admin1`
    FOREIGN KEY (`id_admin`)
    REFERENCES `mydb`.`admin` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_Usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recorridos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recorridos` (
  `id_recorridos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `id_guia` INT NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`id_recorridos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `id_reservas` INT NOT NULL AUTO_INCREMENT,
  `fecha_reserva` DATE NOT NULL,
  `id_recorrido` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_reservas`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_recorrido_idx` (`id_recorrido` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_recorrido`
    FOREIGN KEY (`id_recorrido`)
    REFERENCES `mydb`.`recorridos` (`id_recorridos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guia` (
  `id_guia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_recorrido` INT NOT NULL,
  PRIMARY KEY (`id_guia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guia_recorridos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guia_recorridos` (
  `id_guia` INT NOT NULL,
  `id_recorridos` INT NOT NULL,
  PRIMARY KEY (`id_guia`, `id_recorridos`),
  INDEX `fk_guia_has_recorridos_recorridos1_idx` (`id_recorridos` ASC) VISIBLE,
  INDEX `fk_guia_has_recorridos_guia1_idx` (`id_guia` ASC) VISIBLE,
  CONSTRAINT `fk_guia_has_recorridos_guia1`
    FOREIGN KEY (`id_guia`)
    REFERENCES `mydb`.`guia` (`id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guia_has_recorridos_recorridos1`
    FOREIGN KEY (`id_recorridos`)
    REFERENCES `mydb`.`recorridos` (`id_recorridos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`blog` (
  `id_blog` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `imagen` BLOB NULL,
  `cuerpo` VARCHAR(45) NOT NULL,
  `admin_id_admin` INT NOT NULL,
  PRIMARY KEY (`id_blog`),
  INDEX `fk_blog_admin1_idx` (`admin_id_admin` ASC) VISIBLE,
  CONSTRAINT `fk_blog_admin1`
    FOREIGN KEY (`admin_id_admin`)
    REFERENCES `mydb`.`admin` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
