-- MySQL Script generated by MySQL Workbench
-- Sat Oct 29 19:43:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guia` (
  `Id_guia` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Id_recorrido` INT NOT NULL,
  PRIMARY KEY (`Id_guia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `Id_admin` INT NOT NULL AUTO_INCREMENT,
  `Guia_Id_guia` INT NOT NULL,
  PRIMARY KEY (`Id_admin`, `Guia_Id_guia`),
  INDEX `fk_Administrador_Guia1_idx` (`Guia_Id_guia` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Guia1`
    FOREIGN KEY (`Guia_Id_guia`)
    REFERENCES `mydb`.`Guia` (`Id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Id_cliente` INT NOT NULL,
  `Estado_suscripcion` VARCHAR(60) NOT NULL,
  `Id_reserva` INT NOT NULL,
  PRIMARY KEY (`Id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido` VARCHAR(30) NOT NULL,
  `Edad` INT NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Id_admin` INT NOT NULL,
  `Id_cliente` INT NOT NULL,
  `Id_guia` INT NOT NULL,
  PRIMARY KEY (`Id_usuario`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `Id_admin_idx` (`Id_admin` ASC) VISIBLE,
  INDEX `Id_cliente_idx` (`Id_cliente` ASC) VISIBLE,
  CONSTRAINT `Id_admin`
    FOREIGN KEY (`Id_admin`)
    REFERENCES `mydb`.`Administrador` (`Id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_cliente`
    FOREIGN KEY (`Id_cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recorridos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recorridos` (
  `Id_recorrido` INT NOT NULL AUTO_INCREMENT,
  `Id_guia` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `nivel_de_recorrido` VARCHAR(45) NOT NULL,
  `fecha_de_recorrido` VARCHAR(45) NOT NULL,
  `nombre_de_guia` VARCHAR(45) NOT NULL,
  `costo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_recorrido`),
  INDEX `Id_guia_idx` (`Id_guia` ASC) VISIBLE,
  CONSTRAINT `Id_guia`
    FOREIGN KEY (`Id_guia`)
    REFERENCES `mydb`.`Guia` (`Id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `Id_reserva` INT NOT NULL AUTO_INCREMENT,
  `Id_recorrido` INT NOT NULL,
  `Id_cliente` INT NOT NULL,
  `fecha_reserva` VARCHAR(45) NOT NULL,
  `nro_de_reserva` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_reserva`),
  INDEX `Id_recorrido_idx` (`Id_recorrido` ASC) VISIBLE,
  INDEX `Id_cliente_idx` (`Id_cliente` ASC) VISIBLE,
  CONSTRAINT `Id_recorrido`
    FOREIGN KEY (`Id_recorrido`)
    REFERENCES `mydb`.`Recorridos` (`Id_recorrido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Id_cliente`
    FOREIGN KEY (`Id_cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Recorridos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Recorridos` (
  `Cliente_Id_cliente` INT NOT NULL,
  `Recorridos_Id_recorrido` INT NOT NULL,
  PRIMARY KEY (`Cliente_Id_cliente`, `Recorridos_Id_recorrido`),
  INDEX `fk_Cliente_has_Recorridos_Recorridos1_idx` (`Recorridos_Id_recorrido` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Recorridos_Cliente1_idx` (`Cliente_Id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Recorridos_Cliente1`
    FOREIGN KEY (`Cliente_Id_cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Recorridos_Recorridos1`
    FOREIGN KEY (`Recorridos_Id_recorrido`)
    REFERENCES `mydb`.`Recorridos` (`Id_recorrido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

